config/routes.rb
Rails.application.routes.draw do
  root to: 'wikis#index'

  resources :wikis do
    resources :pages, path: 'p'
    resource :sidebar, except: %i(show new create destroy)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :wiki, required: true

  RESERVED_BLOBS = %w(index new).freeze

  validates :blob, presence: true, length: { maximum: 255 }, uniqueness: { scope: %i(wiki_id) },
    exclusion: { in: RESERVED_BLOBS }
  validates :name, presence: true, length: { maximum: 255 }
  validates :content, presence: true

  scope :top, -> { where(blob: 'welcome') }

  class << self
    def urlnize(value)
      return unless value

      # 0-9, a-z, A-Z, - 以外はすべて `_` にする
      value.gsub(/[^[0-9a-zA-Z\-]]/, ?_)
    end

    def welcome
      find_by!(blob: 'welcome')
    end
  end

  def to_param
    blob
  end

  def blob=(value)
    super(self.class.urlnize(value))
  end
end

app/models/sidebar.rb
class Sidebar < ActiveRecord::Base
  belongs_to :wiki, required: true

  validates :content, presence: true
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  has_many :pages, dependent: :destroy

  has_one :sidebar

  validates :blob, presence: true, length: { maximum: 255 }, uniqueness: true
  validates :name, presence: true, length: { maximum: 255 }

  after_create :create_welcome_page
  after_create :create_sidebar

  def to_param
    blob
  end

  private

  def create_welcome_page
    pages.create!(
      blob: 'welcome',
      name: 'Welcome',
      content: <<MARKDOWN
# Welcome!!
新しい wiki がつくられました!
おめでとうございます!!

このページは常にトップとして表示されます。
お好きなように編集してください。

以下にお役立ち情報を載せますので、ご活用ください(TODO):
- 書式について(markdown)
- 絵文字
MARKDOWN
    )
  end

  def create_sidebar
    create_sidebar!(
      content: <<MARKDOWN
各 wiki にひとつずつ、サイドバーがついてきます。
グローバルナビゲーションや、ブックマークとして便利に使ってください。
MARKDOWN
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'page'

  before_action :set_wiki
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = @wiki.pages.build(
      name: params[:name],
      blob: params[:blob]
    )
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = @wiki.pages.build(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to [@wiki, @page], notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to [@wiki, @page], notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_wiki
    @wiki = Wiki.find_by!(blob: params[:wiki_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = @wiki.pages.find_by!(blob: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:blob, :name, :content)
  end
end

app/controllers/sidebars_controller.rb
class SidebarsController < ApplicationController
  layout 'page'

  before_action :set_wiki
  before_action :set_sidebar

  def edit
  end

  def update
    if @sidebar.update(page_params)
      redirect_to wiki_page_path(@wiki, @wiki.pages.welcome), notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_wiki
    @wiki = Wiki.find_by(blob: params[:wiki_id])
  end

  def set_sidebar
    @sidebar = @wiki.sidebar
  end

  def page_params
    params.require(:sidebar).permit(:content)
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  layout 'page', only: %i(show)

  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = Wiki.all
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
    redirect_to wiki_page_path(@wiki, @wiki.pages.welcome)
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = Wiki.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to wiki_page_path(@wiki, @wiki.pages.welcome) }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_wiki
    @wiki = Wiki.find_by!(blob: params[:id] || params[:wiki_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wiki_params
    params.require(:wiki).permit(:blob, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  class SaraRenderer < Redcarpet::Render::HTML
    include Rails.application.routes.url_helpers

    def initialize(wiki, options = {})
      @wiki = wiki
      super(options)
    end

    # syntax highlight by pygments
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ['code', language, sha].join('-') do
        Pygments.highlight(code, lexer:language)
      end
    end

    def postprocess(full_document)
      # wiki link 処理
      regex = /\[\[(.*?)(\|(.*))?\]\]/
      full_document.gsub(regex) {
        target_name = $1
        target_blob = $3

        link, html_class =
          begin
            if target_blob.nil?
              # [[aaa]] の形
              page = @wiki.pages.find_by(name: target_name)
              if page
                [wiki_page_path(@wiki, page), '']
              else
                # TODO pass the name
                [new_wiki_page_path(@wiki, name: target_name, blob: Page.urlnize(target_name)), 'new-page']
              end
            else
              # [[aaa|bbb]] の形
              page = @wiki.pages.find_by(blob: Page.urlnize(target_blob))
              if page
                [wiki_page_path(@wiki, page), '']
              else
                # TODO pass the name and the blob
                [new_wiki_page_path(@wiki, name: target_name, blob: target_blob), 'new-page']
              end
            end
          end

        ApplicationController.helpers.link_to($1, link, class: html_class)
      }
    end
  end

  def markdown(wiki, text)
    renderer = SaraRenderer.new(wiki, hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      no_intra_emphasis: true,
      strikethrough: true,
      superscript: true,
      tables: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title Sara
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/page.html.haml
!!!
%html
  %head
    = render 'shared/head'
  %body
    #layout.pure-g
      = render 'shared/nav'
      #side.pure-u-1
        = yield(:side)
      #main.pure-u-1
        = yield

app/views/pages/_form.html.haml
= form_for([@wiki, @page], html: { class: 'pure-form pure-form-stacked' }) do |f|
  - if @page.errors.any?
    #error_explanation
      %h2
        = pluralize(@page.errors.count, "error")
        prohibited this page from being saved:
      %ul
        - @page.errors.full_messages.each do |message|
          %li= message
  %fieldset
    .pure-g
      .pure-u-1-2
        = f.label :name
        = f.text_field :name, class: 'pure-input-2-3'

      .pure-u-1-2
        = f.label :blob, 'URL'
        = f.text_field :blob, class: 'pure-input-2-3'

    .pure-g
      .pure-u-1-2
        = f.label :content
        = f.text_area :content, class: 'pure-input-1', rows: 30

      .pure-u-1-2
        %p
          ｺｺにﾌﾟﾚﾋﾞｭｰされるﾖﾃｲ

    = f.submit class: 'pure-button pure-button-primary'

app/views/pages/edit.html.haml
= render 'shared/wiki_side'

.header.markdown-content-header
  %h1 編集

.markdown-content-body
  = render 'form'

app/views/pages/index.html.haml
= render 'shared/wiki_side'

.markdown-content-body
  %ul
    - @wiki.pages.each do |page|
      %li
        = link_to page.name, wiki_page_path(@wiki, page)

app/views/pages/new.html.haml
= render 'shared/wiki_side'

.header.markdown-content-header
  %h1 新規

.markdown-content-body
  = render 'form'

app/views/pages/show.html.haml
= render 'shared/wiki_side'

.markdown-content-header.pure-g
  .pure-u-1-2
    %h1.markdown-content-title= @page.name
    %p.markdown-content-subtitle
      From
      %a Tilo Mitra
      at
      %span= @page.updated_at
  .markdown-content-controls.pure-u-1-2
    = link_to 'edit', edit_wiki_page_path(@wiki, @page), class: 'secondary-button pure-button'
    %button.pure-button.pure-button-disabled star
    %button.pure-button.pure-button-disabled comments
.markdown-content-body
  ~ markdown(@wiki, @page.content)

app/views/shared/_head.html.haml
%meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
%meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
%title Sara
%link{href: "https://fonts.googleapis.com/css?family=Raleway", rel: "stylesheet", type: "text/css"}/
= stylesheet_link_tag    'application', media: 'all'
= javascript_include_tag 'application'
= csrf_meta_tags

app/views/shared/_nav.html.haml
#nav.pure-u
  %a.nav-menu-button{href: "#"} Menu
  .nav-inner
    = link_to 'TOPにもどる', root_path, class: 'primary-button pure-button'

    -# TODO なんか思いついたらやる
    -# .pure-menu
    -#   %ul.pure-menu-list
    -#     %li.pure-menu-item
    -#       %a.pure-menu-link{href: "#"}
    -#         Inbox
    -#         %span.email-count (2)
    -#     %li.pure-menu-item
    -#       %a.pure-menu-link{href: "#"} Important
    -#     %li.pure-menu-item
    -#       %a.pure-menu-link{href: "#"} Sent
    -#     %li.pure-menu-item
    -#       %a.pure-menu-link{href: "#"} Drafts
    -#     %li.pure-menu-item
    -#       %a.pure-menu-link{href: "#"} Trash

        -# TODO 将来的にお気に入りとかで使えそう
        -# %li.pure-menu-heading Labels
        -# %li.pure-menu-item
        -#   %a.pure-menu-link{href: "#"}
        -#     %span.email-label-personal>
        -#     Personal
        -# %li.pure-menu-item
        -#   %a.pure-menu-link{href: "#"}
        -#     %span.email-label-work>
        -#     Work
        -# %li.pure-menu-item
        -#   %a.pure-menu-link{href: "#"}
        -#     %span.email-label-travel>
        -#     Travel

app/views/shared/_wiki_side.html.haml
= content_for :side do
  .side-content-header
    %h1.side-content-title
      = @wiki.name
      wiki

    .pure-g
      .pure-u-1-4
        = link_to '新規', new_wiki_page_path(@wiki), class: 'pure-button button-small'
      .pure-u-1-4
        = link_to '一覧', wiki_pages_path(@wiki), class: 'pure-button button-small'
      .pure-u-1-2
        = link_to 'サイドバーの編集', edit_wiki_sidebar_path(@wiki), class: 'pure-button button-small'

  .side-content-body
    ~ markdown(@wiki, @wiki.sidebar.content)

app/views/sidebars/edit.html.haml
= render 'shared/wiki_side'

.header.markdown-content-header
  %h1 サイドバーの編集

.markdown-content-body
  = form_for([@wiki, @sidebar], html: { class: 'pure-form pure-form-stacked' }) do |f|
    - if @sidebar.errors.any?
      #error_explanation
        %h2
          = pluralize(@sidebar.errors.count, "error")
          prohibited this page from being saved:
        %ul
          - @sidebar.errors.full_messages.each do |message|
            %li= message
    %fieldset
      .pure-g
        .pure-u-1-2
          = f.label :content
          = f.text_area :content, class: 'pure-input-1', rows: 30

        .pure-u-1-2
          %p
            ｺｺにﾌﾟﾚﾋﾞｭｰされるﾖﾃｲ

      = f.submit class: 'pure-button pure-button-primary'

app/views/wikis/_form.html.haml
= form_for(@wiki) do |f|
  - if @wiki.errors.any?
    #error_explanation
      %h2
        = pluralize(@wiki.errors.count, "error")
        prohibited this wiki from being saved:
      %ul
        - @wiki.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :blob
    %br/
    = f.text_field :blob
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/wikis/edit.html.haml
%h1 Editing Wiki
= render 'form'
= link_to 'Show', @wiki
|
= link_to 'Back', wikis_path

app/views/wikis/index.html.haml
.header
  %h1
    wikis
  %h2
    here is many wikis
= link_to 'New Wiki', new_wiki_path, class: 'pure-button pure-button-primary'

- @wikis.each do |wiki|
  .wiki-list.pure-g
    .pure-u-1-2
      %h2
        = link_to wiki.name, wiki_path(wiki)
    .pure-u-1-2
      = link_to 'edit', edit_wiki_path(wiki), class: 'pure-button'

app/views/wikis/new.html.haml
%h1 New Wiki
= render 'form'
= link_to 'Back', wikis_path

app/views/wikis/show.html.haml
= render 'shared/wiki_side'

.markdown-content-body
  = link_to 'New Page', new_wiki_page_path(@wiki), class: 'pure-button pure-button-primary'

  %ul
    - @wiki.pages.each do |page|
      %li
        = link_to page.name, wiki_page_path(@wiki, page)